### ISSUE TITLE
虽然可以运行，但是报错，说是main函数重复定义了，因为main.go里已经有个main函数了

### ISSUE THREAD

**Issue by medmin** [vvanglro/gin-ent#1]
大佬请问这个问题怎么解决，谢谢

**Comment by vvanglro** [comment]
我这边并没有报错, 可以提供下更多的信息吗

**Comment by medmin** [comment]
哦， 我看到您在`cli.go`里写了：

```
//go:build ignore
// +build ignore
```

似乎这个是没报错的原因

**Comment by vvanglro** [comment]
是的
https://stackoverflow.com/questions/67650677/how-to-ignore-a-go-file-in-a-module
